### ISSUE TITLE
Add new vehicles

### ISSUE THREAD

**Issue by agateau** [agateau/tinywheels#5]
Ideas:

- [ ] Fire truck
- [ ] Santa Claus sled
- [ ] Harvester
- [ ] Semitrailer
- [ ] 3-wheeled bike
- [ ] Taxi
- [ ] Police car
- [ ] A-Team truck
- [x] Roadster
- [ ] Jeep
- [ ] Scoobidoo Van
- [ ] Duke of Hazzard
- [ ] Ghostbusters car
- [ ] Bug Beetle
- [ ] K2000
- [ ] Starsky & Hutch
- [ ] Batman begins batmobile

**Comment by Dariasteam** [comment]
How about the DeLorean?

**Comment by revuwa** [comment]
Would love to see the DeLorean (back to the future edition), Ecto-1 (Ghostbusters) and K2000, too.
As additional iead, the "General Lee" (from "The Dukes of Hazzard") came into my mind.

**Comment by agateau** [comment]
I originally had "General Lee" on my list, but I don't want to have a car with a confederate flag in the game.

An anti-gravity vehicle would be great, but I would have to evaluate if it is possible using the game engine: it would have to behave differently from wheeled vehicles for it to be interesting.

**Comment by OffifialMITX** [comment]
A motorcycle maybe? I think that low density and acceleration time and high ground contact would make for interesting gameplay. As a counterbalance it should probably have less momentum, bigger problems with sand, water and ice and less momentum gain from the boosters.

**Comment by Dtrieb** [comment]
How can we make self cars?

**Comment by agateau** [comment]
I won't do 2-wheeled motorcycles because that would require handling leaning when turning. A 3 wheeled one would be doable, though.

**Comment by agateau** [comment]
> How can we make self cars?

This is not possible at the moment, the car list is hard-coded in the game.

**Comment by ilaydaozdemir99** [comment]
hey @agateau can I contribute with adding a vehicle ?

**Comment by agateau** [comment]
> hey @agateau can I contribute with adding a vehicle ?

Sure you can! I reserve the right to decide if it fits with my idea of the game though. This document explains the process: https://github.com/agateau/pixelwheels/blob/18d4f3b231865c0179dd633d1845c6201b191251/docs/vehicles.md

**Comment by ilaydaozdemir99** [comment]
Thank you @agateau  but can I ask you some questions ? If you have discord account I can ask them from here

**Comment by agateau** [comment]
@ilaydaozdemir99 sorry for the late answer, I have been busy... I don't use discord enough for it to be useful, but I just enabled Discussions on the repository. Can you post your vehicle idea in the [Ideas category](https://github.com/agateau/pixelwheels/discussions/categories/ideas)?
